# training:
#   lr:
#     type: loguniform
#     values: [0.001, 0.01]
#   # gamma:
#   #   type: uniform
#   #   values: [0.5, 0.9]
#   train_batch_size:
#     type: choice
#     values: [128, 256, 512]
#   # dueling:
#   #   type: choice
#   #   values: [true, false]
#   # double_q:
#   #   type: choice
#   #   values: [true, false]
#   # noisy:
#   #   type: choice
#   #   values: [true, false]
#   n_step:
#     type: choice
#     values: [1, 3, 5, 8]
#   target_network_update_freq:
#     type: choice
#     values: [500, 1000, 3000]
#   num_steps_sampled_before_learning_starts:
#     type: choice
#     values: [1, 50, 100, 1000, 2000]
#   num_atoms:
#     type: choice
#     values: [1, 10, 20, 50]
