defaults:
  - model: screen_size_128_complex






## For SARL DQN with episode based PER
v_min: 0
v_max: 5
noisy: true
lr: 0.00454119
n_step: 4
num_atoms: 10
num_steps_sampled_before_learning_starts: 200000
target_network_update_freq: 3000
train_batch_size: 1
gamma: 0.95

## For SARL PPO
#train_batch_size: 1000


## Older Values


# num_atoms: 51


# train_batch_size: 4000
# lr: 0.00173477
# n_step: 3
# num_atoms: 10
# num_steps_sampled_before_learning_starts: 100
# target_network_update_freq: 500
# train_batch_size: 64




