sim:
  _target_: simfire.sim.simulation.FireSimulation
  config:
    _target_: simfire.utils.config.Config
    config_dict: ${simulation.train}
movements: [none, up, down, left, right]
interactions: [none, fireline]
attributes: [fire_map, elevation, w_0, sigma, delta, M_x]
normalized_attributes: [elevation]
agent_speed: 9
# Defines the class that will be used to monitor and track `ReactiveHarness`.
tracker_partial: 
  _target_: simharness2.utils.analytics_tracker.ReactiveAnalyticsTracker
  _partial_: true
  # Defines the class that will be used to monitor and track `FireSimulation`.
  sim_data_partial:
    _target_: simharness2.utils.analytics_tracker.FireSimulationMetricsTracker
    _partial_: true
    # Defines the class that will be used to monitor and track agent behavior.
    agent_data_partial:
      _target_: simharness2.utils.analytics_tracker.AgentMetricsTracker
      _partial_: true
reward_cls: 
  _target_: simharness2.rewards.base_reward.ComprehensiveReward
initial_agent_pos: [15, 15]
randomize_initial_agent_pos: false
benchmark_sim: ${.sim}
# TODO: Provide higher level option to specify use_benchmark_sim, etc. (??)
# NOTE: To disable usage of `benchmark_sim`, set value to `null` (below).
# benchmark_sim: null
action_space_partial:
  _partial_: true
  _target_: gymnasium.spaces.Discrete
# sim_seeds_to_randomize: [fire_initial_position]
# sim_seeds_to_randomize: [fire_start_location, elevation, fuel, wind_speed, wind_direction]
